import type * as GeoJSON from 'geojson'

// Shapes of the JSON files in public/data (generated by scripts/build-data.mjs).

export interface Stat {
  value: number
  year?: number
  source: string
  /** Computed from the map geometry rather than taken from statistics. */
  approx?: boolean
}

export interface Capital {
  ja: string
  en: string
  lat: number
  lng: number
  rank: number
  note?: string
}

export type CountryStatus = 'independent' | 'dependency' | 'other'

export interface CountryInfo {
  ja: string
  jaFormal?: string
  en: string
  enFormal?: string
  iso2?: string
  status: CountryStatus
  notRecognizedByJapan?: boolean
  /** ADM0_A3 code of the sovereign state, for dependencies. */
  sovereign?: string
  continent: string
  subregion: string
  label: { lat: number; lng: number; rank: number }
  capitals: Capital[]
  population?: Stat
  area: Stat
}

export interface CountryInfoFile {
  sources: Record<string, string>
  countries: Record<string, CountryInfo>
}

export interface CountryFeature {
  type: 'Feature'
  properties: { id: string }
  geometry: GeoJSON.Polygon | GeoJSON.MultiPolygon
}

export interface PlaceLabel {
  ja: string
  en?: string
  lat: number
  lng: number
  rank: number
  elevation?: number
}

export interface GeoLine {
  ja: string
  en: string
  /** Parts of the line as [lat, lng] pairs. */
  points: [number, number][][]
}

export interface AppData {
  countries: CountryFeature[]
  info: CountryInfoFile
  rivers: GeoJSON.FeatureCollection<GeoJSON.LineString | GeoJSON.MultiLineString, { rank: number }>
  riverLabels: PlaceLabel[]
  ranges: PlaceLabel[]
  peaks: PlaceLabel[]
  geoLines: GeoLine[]
}
